// 1. CRUD Mpasi
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Bubur Hati Ayam",
  "porsi": 3,
  "bahan": {
    "nasi": "60gr",
    "hati ayam": "30gr",
    "minyak jagung": "7,5ml",
    "garam": "secukupnya (jika diperlukan)"
  },
  "cara_masak": [
    "Tumis bumbu halus hingga harum.",
    "Masukkan hati ayam, aduk hingga berubah warna.",
    "Masukkan bayam dan garam secukupnya.",
    "Masukkan nasi, aduk hingga teksturnya sesuai keinginan."
  ],
  "kategori": "6-8 bulan",
  "gambar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGpeLd7_frYsELL1erPmeJ04NjZYEEoA_6bpHkFIi7Bw&s",
  "kalori": 67,
  "protein": 3,
  "lemak": 6,
  "karbohidrat": 6
}

###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Ayam Kecap",
  "porsi": 3,
  "bahan": {
    "beras": "60gr",
    "kaldu ayam": "300ml",
    "daging ayam": "100gr",
    "Kecap manis": "2 sdm",
    "minyak jagung": "1,5 sdm"
  },
  "cara_masak": [
    "Kupas dan potong kentang menjadi potongan kecil-kecil.",
    "Rebus kentang hingga empuk, lalu tiriskan.",
    "Kocok telur dan tambahkan ke dalam kentang yang telah dihaluskan.",
    "Panaskan kaldu sapi dan tambahkan ke dalam campuran kentang dan telur. Aduk hingga merata.",
    "Masak campuran tersebut dengan api kecil hingga mengental dan menjadi bubur yang lembut.",
    "Angkat dan biarkan dingin sebelum disajikan kepada bayi."
  ],
  "kategori": "9-12 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/b7e800b9e1c73f32/680x482cq70/nasi-tim-ayam-kecap-mpasi-9-foto-resep-utama.jpg",
  "kalori": 128,
  "protein": 5.8,
  "lemak": 5.4,
  "karbohidrat": 13.6
}

###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Bubur Patin",
  "porsi": 3,
  "bahan": {
    "Nasi": "60 gram",
    "Hati Ayam": "30 gram",
    "Minyak Jagung": "7.5 ml",
    "Bawang Bombai": "3 iris",
    "Jahe": "1/3 cm",
    "Daun salam" : "1 lembar",
    "Tomat, potong kecil-kecil": "10 gram"
  },
  "cara_masak": [
    "1, Lumuri ikan patin dan hati ayam dengan jeruk nipis dan garam, diamkan 15 menit",
    "2. Campur ikan patin dan hati ayam dengan bumbu halus, tambahkan tomat, bawang bombai, jahe, seledri, daun salam, dan daun jeruk",
    "3. Kukus hingga matang",
    "4. Ketika akan dicampur dengan nasi, ambil daun salam dan daun jeruknya. Lalu saring hingga teksturnya sesuai yang diinginkan."
  ],
  "kategori": "6-8 bulan",
  "gambar": "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1634025439/7eb31d6a3a0418b558d1086f346f1b3c1a880bed7346f4223e15227a763a1827.jpg",
  "kalori": 80,
  "protein": 4.3,
  "lemak": 4.3,
  "karbohidrat": 6
}
###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Bubur Daging Sapi",
  "porsi": 3,
  "bahan": {
    "Nasi": "60 gram",
    "Daging Sapi Giling": "50 gram",
    "Minyak Jagung": "7.5 ml",
    "Bayam, rebus matang, iris kecil-kecil": "15 gram",
    "Minyak Kelapa": "7.5 ml",
    "Garam" : "Secukupnya"
  },
  "cara_masak": [
    "1. Kukus daging sapi giling yang sudah dicampur bumbu halus di dalam wadah tahan panas hingga matang",
    "2. Tambahkan bayam",
    "3. Masukkan minyak kelapa dan garam secukupnya",
    "4. Ketika akan dicampur dengan nasi, ambil daun salam dan daun jeruknya. Lalu saring hingga teksturnya sesuai yang diinginkan."
  ],
  "kategori": "6-8 bulan",
  "gambar": "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1634025439/7eb31d6a3a0418b558d1086f346f1b3c1a880bed7346f4223e15227a763a1827.jpg",
  "kalori": 80,
  "protein": 4.3,
  "lemak": 4.3,
  "karbohidrat": 6
}

###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Bubur Kakap Tempe",
  "porsi": 3,
  "bahan": {
    "Nasi": "60 gram",
    "Ikan kakap, cincang halus": "45 gram",
    "Tempe": "15 gram",
    "Kaldu Ikan": "250 ml",
    "Minyak Kedelai": "7.5 ml",
    "Bawang Putih" : "1 siung"
  },
  "cara_masak": [
    "1. Lumuri ikan kakap dengan bawang, diamkan selama 15 menit",
    "2. Rebus semua bahan dengan kaldu ikan hingga matang dan lunak",
    "3. Tambahkan nasi, lalu saring hingga teksturnya sesuai yang diinginkan",
    "4. Ketika akan dicampur dengan nasi, ambil daun salam dan daun jeruknya. Lalu saring hingga teksturnya sesuai yang diinginkan."
  ],
  "kategori": "6-8 bulan",
  "gambar": "https://asset-2.tstatic.net/banjarmasin/foto/bank/images/akrobat-bocah-2-tahun_20151229_102409.jpg",
  "kalori": 90,
  "protein": 8,
  "lemak": 3.6,
  "karbohidrat": 6.3
}

###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Bola Nasi",
  "porsi": 3,
  "bahan": {
    "Nasi": "75 gram",
    "Daging ayam, giling": "50 gram",
    "Tahu": "20 gram",
    "Telur, kocok": "1 buah",
    "Tepung Maizena": "2 sdm",
    "Wortel Parut" : "1 siung",
    "Tepung roti" : "secukupnya",
    "Minyak kedelai" : "secukupnya"
  },
  "cara_masak": [
    "1. Campurkan nasi, tahu, wortel, tepung maizena, daging ayam giling, bumbu halus, dan telur kocok",
    "2. Bentuk adonan menjadi bola, lalu kukus selama 15 menit hingga adonan matang",
    "3. Celupkan bola nasi ke dalam telur kocok, lalu gulirkan ke dalam tepung roti hingga semua permukaannya tertutup",
    "4. Goreng hingga berubah warna dan matang"
  ],
  "kategori": "9-12 bulan",
  "gambar": "https://asset-2.tstatic.net/banjarmasin/foto/bank/images/akrobat-bocah-2-tahun_20151229_102409.jpg",
  "kalori": 142,
  "protein": 5.7,
  "lemak": 8.3,
  "karbohidrat": 11
}

###
POST http://localhost:3000/api/mpasi
Content-Type: application/json

{
  "makanan": "Tim Mie Ayam",
  "porsi": 3,
  "bahan": {
    "Mie telur, rebus hingga matang": "150 gram",
    "Daging ayam, cincang": "75 gram",
    "Tahu": "20 gram",
    "Telur ayam": "1 butir",
    "Kaldu ayam": "200 ml",
    "Kecap asin" : "1 sdt",
    "Kecap manis" : "1 sdt",
    "Sawi, iris kecil" : "30 gram",
    "Minyak Canola" : "10 ml",
    "Daun seledri": "secukupnya"
  },
  "cara_masak": [
    "1. Campurkan mie telur yang sudah matang dengan bumbu halus, kecap asin, kecap manis, telur ayam kocok, kaldu ayam, dan daging ayam cincang. Aduk hingga tercampur rata. Tambahkan minyak canola",
    "2. Masukkan campuran mie ke dalam wadah tahan panas, lalu kukus hingga kaldu terserap mie",
    "3. Tambahkan irisan seledri dan sawi, lalu kukus kembali hingga matang",
    "4. Goreng hingga berubah warna dan matang"
  ],
  "kategori": "9-12 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/a6a7786a65dfec53/680x482cq70/tim-mie-ayam-mpasi-10m-foto-resep-utama.webp",
  "kalori": 150,
  "protein": 6.5,
  "lemak": 6.8,
  "karbohidrat": 15
}
###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json

{
  "makanan": "Nasi Ayam Katsu",
  "porsi": 3,
  "bahan": {
    "nasi": "200 gram",
    "daging ayam fillet": "100 gram",
    "wortel": "20 gram",
    "buncis": "20 gram",
    "telur kocok": "1/2 butir",
    "jeruk nipis": "1 buah",
    "tepung panir": "secukupnya",
    "garam": "secukupnya",
    "merica": "secukupnya",
    "minyak goreng": "secukupnya"
  },
  "cara_masak": [
    "1. Rebus daging ayam fillet hingga matang, lalu haluskan.",
    "2. Campurkan daging ayam halus dengan wortel, buncis, telur kocok, garam, dan merica.",
    "3. Bentuk adonan menjadi bulat pipih, lalu gulingkan ke tepung panir.",
    "4. Goreng hingga matang dan kecoklatan.",
    "5. Sajikan dengan nasi dan jeruk nipis."
  ],
  "kategori": "12-23 bulan",
  "gambar": "https://i.ytimg.com/vi/GvVJOVP6MGQ/maxresdefault.jpg",
  "kalori": 186,
  "protein": 7.9,
  "lemak": 8.3,
  "karbohidrat": 20
}
###
POST https://stuntcare.cleverapps.io/api/mpasi

Content-Type: application/json

{
  "makanan": "Tim Kentang Telur",
  "porsi": 3,
  "bahan": {
    "kentang": "150 gram, rebus, haluskan",
    "daging ayam cincang": "50 gram, rebus",
    "wortel parut": "12 sdm",
    "telur": "1 butir, kocok lepas",
    "margarin": "10 gram",
    "garam": "secukupnya"
  },
  "cara_masak": [
    "1. Campur semua bahan, aduk rata.",
    "2. Tambahkan air hingga adonan tenggelam dalam air, lalu masukkan ke dalam wadah tahan panas.",
    "3. Kukus hingga matang."
  ],
  "kategori": "9-12 bulan",
  "gambar": "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:good,w_640,ar_16:9/v1634025439/018115264801f532a73d4381880ea01b.jpg",
  "kalori": 130,
  "protein": 5.8,
  "lemak": 6.4,
  "karbohidrat": 13
}
###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json

{
  "makanan": "Mie Tek-Tek",
  "porsi": 3,
  "bahan": {
    "mie telur": "150 gram, sudah direbus hingga lunak",
    "daging ayam": "100 gram, rebus, potong kecil-kecil",
    "sawi": "30 gram, potong kasar",
    "telur mata sapi": "1 butir",
    "kecap manis": "2 sdm",
    "kecap asin": "1 sdm",
    "minyak kelapa": "15 ml, untuk menumis",
    "garam": "secukupnya",
    "gula": "secukupnya",
    "merica": "secukupnya",
    "bawang daun": "secukupnya, iris tipis",
    "bawang putih": "2 siung",
    "bawang merah": "2 buah",
    "kemiri sangrai": "2 butir"
  },
  "cara_masak": [
    "1. Tumis bumbu halus, lalu masukkan bawang daun hingga harum.",
    "2. Masukkan mi, ayam, dan sawi.",
    "3. Tambahkan kecap manis, kecap asin, gula, garam, dan merica secukupnya, lalu aduk hingga tercampur rata.",
    "4. Hidangkan dengan telur mata sapi."
  ],
  "kategori": "12-23 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/438a7504c8046be6/680x482cq70/mie-tek-tek-udang-kuah-mpasi-1-y-foto-resep-utama.webp",
  "kalori": 280,
  "protein": 9.4,
  "lemak": 8.6,
  "karbohidrat": 28.4
}
###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json

{
  "makanan": "Semur Ayam",
  "porsi": 3,
  "bahan": {
    "nasi": "60 gram",
    "daging ayam cincang": "300 ml",
    "tahu putih cincang": "100 gram",
    "wortel parut": "4 sdm",
    "kecap manis": "2 sdm",
    "minyak jagung": "1 sdm",
    "Merica dan garam": "secukupnya",
    "Bawang putih": "1 siung",
    "Bawang merah": "1 buah"
  },
  "cara_masak": [
    "1. Tumis bumbu halus hingga harum, lalu masukkan daging ayam cincang.",
    "2. Tambahkan wortel, kecap manis, dan garam secukupnya. Masak kembali.",
    "3. Masukkan nasi, tumis ayam, dan tahu putih ke dalam wadah tahan panas, tambahkan kaldu ayam. Kukus hingga matang dan kaldu terserap."
  ],
  "kategori": "9-12 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/0788c9cea765b369/680x482cq70/semur-ayam-mpasi-15-bulan-foto-resep-utama.webp",
  "kalori": 120,
  "protein": 4.8,
  "lemak": 6.1,
  "karbohidrat": 13
}

###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json
{
  "makanan": "Nasi Goreng Udang",
  "porsi": 3,
  "bahan": {
    "nasi": "150 gram",
    "udang": "100 gram, buang kulitnya",
    "tepung maizena": "1/2 sdt",
    "telur": "1 butir, kocok",
    "kacang polong": "30 gram",
    "minyak jagung": "15 ml, untuk menumis",
    "daun bawang": "secukupnya, iris tipis",
    "garam": "secukupnya",
    "bawang putih": "2 siung",
    "bawang merah": "1 butir"
  },
  "cara_masak": [
    "1. Lumuri udang dengan garam dan tepung maizena, diamkan sekitar 15 menit.",
    "2. Goreng udang hingga matang, masukkan telur dan kacang polong, lalu diorak-arik. Sisihkan.",
    "3. Tumis bumbu halus hingga harum, masukkan daun bawang.",
    "4. Tambahkan nasi dan garam secukupnya, aduk rata.",
    "5. Masukkan udang, orak-arik telur, dan kacang polong, lalu aduk hingga tercampur rata."
  ],
  "kategori": "12-23 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/5816a9a6366493df/680x482cq70/menu-mpasi-12-nasi-goreng-udang-ala-dr-meta-hanindhita-foto-resep-utama.webp",
  "kalori": 183,
  "protein": 11.2,
  "lemak": 7.6,
  "karbohidrat": 17
}
###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json
{
  "makanan": "Sup Ayam",
  "porsi": 3,
  "bahan": {
    "nasi": "150 gram",
    "dada ayam": "100 gram, rebus, suwir",
    "kaldu ayam": "750 ml",
    "jagung manis pipil": "30 gram",
    "wortel": "1 batang, potong kotak",
    "daun bawang": "1 batang, potong kecil",
    "tomat": "1/2 buah, potong kecil",
    "margarin": "2 sdm",
    "garam": "secukupnya",
    "merica": "secukupnya",
    "pala": "secukupnya",
    "seledri": "secukupnya"
  },
  "cara_masak": [
    "1. Rebus kaldu ayam dengan wortel, jagung manis, seledri, dan daun bawang hingga harum.",
    "2. Masukkan dada ayam suwir, garam, merica, dan pala secukupnya, masak hingga mendidih.",
    "3. Masukkan tomat, masak hingga layu.",
    "4. Sajikan dengan nasi dan mentega yang dilelehkan di atas nasi."
  ],
  "kategori": "12-23 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/38948bcdadb1fe69/680x482cq70/sup-ayam-mpasi-9-bulan-foto-resep-utama.webp",
  "kalori": 210,
  "protein": 10.1,
  "lemak": 8.2,
  "karbohidrat": 24.2
}
###
POST https://stuntcare.cleverapps.io/api/mpasi
Content-Type: application/json

{
  "makanan": "Nasi Campur",
  "porsi": 3,
  "bahan": {
    "nasi": "200 gram",
    "telur": "3 butir, kocok lepas",
    "daun bawang": "1 batang, iris tipis",
    "bawang bombai": "1/2 buah, cincang kasar",
    "wortel": "15 gram, cincang halus",
    "daging ayam giling": "30 gram, rebus matang",
    "minyak jagung": "3 sdm",
    "merica": "secukupnya",
    "garam": "secukupnya",
    "bawang putih": "2 siung",
    "bawang merah": "1 siung"
  },
  "cara_masak": [
    "1. Campur telur dengan daun bawang, bawang bombai, wortel, daging ayam giling, garam, merica, dan bumbu halus. Aduk hingga tercampur rata.",
    "2. Goreng dengan minyak jagung hingga matang.",
    "3. Sajikan dengan nasi."
  ],
  "kategori": "12-23 bulan",
  "gambar": "https://img-global.cpcdn.com/recipes/46269b51d18e363b/680x482cq70/nasi-campur-campur-dadakan-mpasi-tak-terduga-foto-resep-utama.webp",
  "kalori": 230,
  "protein": 10.8,
  "lemak": 12.1,
  "karbohidrat": 18.8
}
